//
//  ClipboardManager.swift
//  Passover
//
//  Created by Aakash Solanki on 24/08/24.
//


import Foundation
import AppKit
import os

class ClipboardManager {
    private var pasteboard = NSPasteboard.general
    private var changeCount: Int
    private var isAddingData: Bool = false
    private var timer:Timer? = nil
    private var lastPublishedPayload: String?
    let sensitiveTypes = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType"
    ]
    // TODO: If user hasn't touched Mac for 30 seconds, stop checking every second.
    // Drop to "Slow Poll" mode (e.g., every 5-10 seconds)

    
    var onClipboardUpdate: ((ClipboardMessage) -> Void)?

    init() {
        changeCount = pasteboard.changeCount
        startMonitoringClipboard()
        Logger.connection.info("Clipboard manager started!")
    }
    
    deinit{
        timer?.invalidate()
        timer = nil
    }
    
    func stopMonitoring() {
        timer?.invalidate()
        timer = nil
        Logger.connection.info("Clipboard monitoring stopped")
    }
    
    private func startMonitoringClipboard() {
        timer = Timer.scheduledTimer(withTimeInterval: 1, repeats: true) { [weak self] _ in
            self?.checkClipboard()
        }
    }

    private func checkClipboard() {
        guard !isAddingData, pasteboard.changeCount != changeCount else { return }
        
        if let types = pasteboard.types?.map({ $0.rawValue }),
           !types.filter({ sensitiveTypes.contains($0) }).isEmpty {
            Logger.connection.info("Ignored sensitive/transient clipboard data")
            changeCount = pasteboard.changeCount
            return
        }
        
        if pasteboard.canReadItem(withDataConformingToTypes: ["public.png"]),
           let imageData = pasteboard.data(forType: .png) {
            Logger.connection.info("Clipboard image (PNG)")
            handlePayload(imageData.base64EncodedString(), type: .img)

        } else if pasteboard.canReadItem(withDataConformingToTypes: ["public.tiff"]),
            let imageData = pasteboard.data(forType: .tiff) {
            Logger.connection.info("Clipboard image (TIFF)")
            handlePayload(imageData.base64EncodedString(), type: .img)

        } else if let text = pasteboard.string(forType: .string) {
            Logger.connection.info("Clipboard text")
            handlePayload(text, type: .txt)
        }
        
        changeCount = pasteboard.changeCount
    }

    func addDataToClipboard(data: ClipboardMessage) {
        print("adding to clipborad")
        isAddingData = true
        defer {
            isAddingData = false
        }
        pasteboard.clearContents()
        
        if(data.type == .txt){
            pasteboard.setString(data.content, forType: .string)
        }
        else if(data.type == .img){
            Logger.connection.info("Got image data")
//            pasteboard.setData(image.tiffRepresentation, forType: .tiff)
        }
        else{
            return
        }
        changeCount = pasteboard.changeCount
        self.isAddingData = false
    }

    
    private func handlePayload(_ payload: String, type: ClipboardMessage.ClipboardContentType) {
            if lastPublishedPayload == payload {
                Logger.connection.debug("Duplicate clipboard payload ignored")
                return
            }
            lastPublishedPayload = payload

            if type == .img,
               let decodedData = Data(base64Encoded: payload),
               let image = NSImage(data: decodedData),
               let pngData = convertToPNG(image: image) {

                publishData(text: pngData.base64EncodedString(), type: .img)
            } else {
                publishData(text: payload, type: type)
            }
        }
    

    private func convertToPNG(image: NSImage) -> Data? {
        guard let tiffData = image.tiffRepresentation else { return nil }
        guard let bitmap = NSBitmapImageRep(data: tiffData) else { return nil }
        return bitmap.representation(using: .png, properties: [:])
    }

    
    private func publishData(text: String, type: ClipboardMessage.ClipboardContentType){
        let clipboardData = ClipboardMessage.with{
            $0.content = text
            $0.type = type
        }
        
        onClipboardUpdate?(clipboardData)
    }
}

