// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: Message.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

/// package com.example.bleexample;

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct Message: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var timestampMs: Int64 = 0

  var messageID: String = String()

  var originatorID: String = String()

  var payload: Message.OneOf_Payload? = nil

  var clipboard: ClipboardMessage {
    get {
      if case .clipboard(let v)? = payload {return v}
      return ClipboardMessage()
    }
    set {payload = .clipboard(newValue)}
  }

  var mediaControl: MediaControlMessage {
    get {
      if case .mediaControl(let v)? = payload {return v}
      return MediaControlMessage()
    }
    set {payload = .mediaControl(newValue)}
  }

  var playbackInfo: MediaPlaybackInfo {
    get {
      if case .playbackInfo(let v)? = payload {return v}
      return MediaPlaybackInfo()
    }
    set {payload = .playbackInfo(newValue)}
  }

  var fileHeader: FileHeader {
    get {
      if case .fileHeader(let v)? = payload {return v}
      return FileHeader()
    }
    set {payload = .fileHeader(newValue)}
  }

  var fileChunk: FileChunk {
    get {
      if case .fileChunk(let v)? = payload {return v}
      return FileChunk()
    }
    set {payload = .fileChunk(newValue)}
  }

  var statusRequest: FileStatusRequest {
    get {
      if case .statusRequest(let v)? = payload {return v}
      return FileStatusRequest()
    }
    set {payload = .statusRequest(newValue)}
  }

  var statusResponse: FileStatusResponse {
    get {
      if case .statusResponse(let v)? = payload {return v}
      return FileStatusResponse()
    }
    set {payload = .statusResponse(newValue)}
  }

  var error: FileTransferError {
    get {
      if case .error(let v)? = payload {return v}
      return FileTransferError()
    }
    set {payload = .error(newValue)}
  }

  var videoChunk: VideoStreamChunk {
    get {
      if case .videoChunk(let v)? = payload {return v}
      return VideoStreamChunk()
    }
    set {payload = .videoChunk(newValue)}
  }

  var artwork: MediaArt {
    get {
      if case .artwork(let v)? = payload {return v}
      return MediaArt()
    }
    set {payload = .artwork(newValue)}
  }

  var heartbeat: Heartbeat {
    get {
      if case .heartbeat(let v)? = payload {return v}
      return Heartbeat()
    }
    set {payload = .heartbeat(newValue)}
  }

  var identity: Identity {
    get {
      if case .identity(let v)? = payload {return v}
      return Identity()
    }
    set {payload = .identity(newValue)}
  }

  var handshake: HandshakeMessage {
    get {
      if case .handshake(let v)? = payload {return v}
      return HandshakeMessage()
    }
    set {payload = .handshake(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum OneOf_Payload: Equatable, Sendable {
    case clipboard(ClipboardMessage)
    case mediaControl(MediaControlMessage)
    case playbackInfo(MediaPlaybackInfo)
    case fileHeader(FileHeader)
    case fileChunk(FileChunk)
    case statusRequest(FileStatusRequest)
    case statusResponse(FileStatusResponse)
    case error(FileTransferError)
    case videoChunk(VideoStreamChunk)
    case artwork(MediaArt)
    case heartbeat(Heartbeat)
    case identity(Identity)
    case handshake(HandshakeMessage)

  }

  init() {}
}

struct Identity: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var deviceID: String = String()

  var deviceName: String = String()

  var publicKeyAgreement: Data = Data()

  var publicKeySignature: Data = Data()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct HandshakeMessage: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var sasConfirmed: Bool = false

  var encryptedGroupKey: Data = Data()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct ClipboardMessage: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var content: String = String()

  var type: ClipboardMessage.ClipboardContentType = .txt

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum ClipboardContentType: SwiftProtobuf.Enum, Swift.CaseIterable {
    typealias RawValue = Int
    case txt // = 0
    case img // = 1
    case UNRECOGNIZED(Int)

    init() {
      self = .txt
    }

    init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .txt
      case 1: self = .img
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    var rawValue: Int {
      switch self {
      case .txt: return 0
      case .img: return 1
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    static let allCases: [ClipboardMessage.ClipboardContentType] = [
      .txt,
      .img,
    ]

  }

  init() {}
}

struct MediaControlMessage: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var action: MediaControlMessage.Action = .playPause

  var volume: Float = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum Action: SwiftProtobuf.Enum, Swift.CaseIterable {
    typealias RawValue = Int
    case playPause // = 0
    case next // = 1
    case previous // = 2
    case volumeSet // = 3
    case UNRECOGNIZED(Int)

    init() {
      self = .playPause
    }

    init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .playPause
      case 1: self = .next
      case 2: self = .previous
      case 3: self = .volumeSet
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    var rawValue: Int {
      switch self {
      case .playPause: return 0
      case .next: return 1
      case .previous: return 2
      case .volumeSet: return 3
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    static let allCases: [MediaControlMessage.Action] = [
      .playPause,
      .next,
      .previous,
      .volumeSet,
    ]

  }

  init() {}
}

struct MediaArt: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var content: Data = Data()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct MediaPlaybackInfo: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var playbackRate: Bool = false

  var duration: Double = 0

  var elapsed: Double = 0

  var title: String = String()

  var album: String = String()

  var artist: String = String()

  var bundle: String = String()

  var volume: Float = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct FileHeader: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var fileID: String = String()

  var filename: String = String()

  var filesizeBytes: Int64 = 0

  var metadata: Data = Data()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct FileChunk: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var fileID: String = String()

  var offset: Int64 = 0

  var data: Data = Data()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct FileStatusRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var fileID: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct FileStatusResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var fileID: String = String()

  var bytesRecieved: Int64 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct FileTransferError: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var fileID: String = String()

  var error: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Heartbeat: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var isMediaPlaying: Bool = false

  var isMacUserActive: Bool = false

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct VideoStreamChunk: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var frame: Data = Data()

  var presentationTimestampUs: Int64 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension Message: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "Message"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}timestamp_ms\0\u{1}clipboard\0\u{1}mediaControl\0\u{1}playbackInfo\0\u{1}fileHeader\0\u{1}fileChunk\0\u{1}statusRequest\0\u{1}statusResponse\0\u{1}error\0\u{1}videoChunk\0\u{1}artwork\0\u{1}heartbeat\0\u{1}identity\0\u{1}handshake\0\u{1}messageId\0\u{1}originatorId\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.timestampMs) }()
      case 2: try {
        var v: ClipboardMessage?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .clipboard(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .clipboard(v)
        }
      }()
      case 3: try {
        var v: MediaControlMessage?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .mediaControl(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .mediaControl(v)
        }
      }()
      case 4: try {
        var v: MediaPlaybackInfo?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .playbackInfo(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .playbackInfo(v)
        }
      }()
      case 5: try {
        var v: FileHeader?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .fileHeader(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .fileHeader(v)
        }
      }()
      case 6: try {
        var v: FileChunk?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .fileChunk(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .fileChunk(v)
        }
      }()
      case 7: try {
        var v: FileStatusRequest?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .statusRequest(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .statusRequest(v)
        }
      }()
      case 8: try {
        var v: FileStatusResponse?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .statusResponse(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .statusResponse(v)
        }
      }()
      case 9: try {
        var v: FileTransferError?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .error(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .error(v)
        }
      }()
      case 10: try {
        var v: VideoStreamChunk?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .videoChunk(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .videoChunk(v)
        }
      }()
      case 11: try {
        var v: MediaArt?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .artwork(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .artwork(v)
        }
      }()
      case 12: try {
        var v: Heartbeat?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .heartbeat(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .heartbeat(v)
        }
      }()
      case 13: try {
        var v: Identity?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .identity(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .identity(v)
        }
      }()
      case 14: try {
        var v: HandshakeMessage?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .handshake(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .handshake(v)
        }
      }()
      case 15: try { try decoder.decodeSingularStringField(value: &self.messageID) }()
      case 16: try { try decoder.decodeSingularStringField(value: &self.originatorID) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.timestampMs != 0 {
      try visitor.visitSingularInt64Field(value: self.timestampMs, fieldNumber: 1)
    }
    switch self.payload {
    case .clipboard?: try {
      guard case .clipboard(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case .mediaControl?: try {
      guard case .mediaControl(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case .playbackInfo?: try {
      guard case .playbackInfo(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    }()
    case .fileHeader?: try {
      guard case .fileHeader(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    }()
    case .fileChunk?: try {
      guard case .fileChunk(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    }()
    case .statusRequest?: try {
      guard case .statusRequest(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
    }()
    case .statusResponse?: try {
      guard case .statusResponse(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
    }()
    case .error?: try {
      guard case .error(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
    }()
    case .videoChunk?: try {
      guard case .videoChunk(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
    }()
    case .artwork?: try {
      guard case .artwork(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 11)
    }()
    case .heartbeat?: try {
      guard case .heartbeat(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 12)
    }()
    case .identity?: try {
      guard case .identity(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 13)
    }()
    case .handshake?: try {
      guard case .handshake(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 14)
    }()
    case nil: break
    }
    if !self.messageID.isEmpty {
      try visitor.visitSingularStringField(value: self.messageID, fieldNumber: 15)
    }
    if !self.originatorID.isEmpty {
      try visitor.visitSingularStringField(value: self.originatorID, fieldNumber: 16)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Message, rhs: Message) -> Bool {
    if lhs.timestampMs != rhs.timestampMs {return false}
    if lhs.messageID != rhs.messageID {return false}
    if lhs.originatorID != rhs.originatorID {return false}
    if lhs.payload != rhs.payload {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Identity: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "Identity"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}deviceId\0\u{1}deviceName\0\u{1}publicKeyAgreement\0\u{1}publicKeySignature\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.deviceID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.deviceName) }()
      case 3: try { try decoder.decodeSingularBytesField(value: &self.publicKeyAgreement) }()
      case 4: try { try decoder.decodeSingularBytesField(value: &self.publicKeySignature) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.deviceID.isEmpty {
      try visitor.visitSingularStringField(value: self.deviceID, fieldNumber: 1)
    }
    if !self.deviceName.isEmpty {
      try visitor.visitSingularStringField(value: self.deviceName, fieldNumber: 2)
    }
    if !self.publicKeyAgreement.isEmpty {
      try visitor.visitSingularBytesField(value: self.publicKeyAgreement, fieldNumber: 3)
    }
    if !self.publicKeySignature.isEmpty {
      try visitor.visitSingularBytesField(value: self.publicKeySignature, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Identity, rhs: Identity) -> Bool {
    if lhs.deviceID != rhs.deviceID {return false}
    if lhs.deviceName != rhs.deviceName {return false}
    if lhs.publicKeyAgreement != rhs.publicKeyAgreement {return false}
    if lhs.publicKeySignature != rhs.publicKeySignature {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension HandshakeMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "HandshakeMessage"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}sasConfirmed\0\u{1}encryptedGroupKey\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.sasConfirmed) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.encryptedGroupKey) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.sasConfirmed != false {
      try visitor.visitSingularBoolField(value: self.sasConfirmed, fieldNumber: 1)
    }
    if !self.encryptedGroupKey.isEmpty {
      try visitor.visitSingularBytesField(value: self.encryptedGroupKey, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: HandshakeMessage, rhs: HandshakeMessage) -> Bool {
    if lhs.sasConfirmed != rhs.sasConfirmed {return false}
    if lhs.encryptedGroupKey != rhs.encryptedGroupKey {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension ClipboardMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "ClipboardMessage"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}content\0\u{1}type\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.content) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.type) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.content.isEmpty {
      try visitor.visitSingularStringField(value: self.content, fieldNumber: 1)
    }
    if self.type != .txt {
      try visitor.visitSingularEnumField(value: self.type, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: ClipboardMessage, rhs: ClipboardMessage) -> Bool {
    if lhs.content != rhs.content {return false}
    if lhs.type != rhs.type {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension ClipboardMessage.ClipboardContentType: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0TXT\0\u{1}IMG\0")
}

extension MediaControlMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "MediaControlMessage"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}action\0\u{1}volume\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.action) }()
      case 2: try { try decoder.decodeSingularFloatField(value: &self.volume) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.action != .playPause {
      try visitor.visitSingularEnumField(value: self.action, fieldNumber: 1)
    }
    if self.volume.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.volume, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: MediaControlMessage, rhs: MediaControlMessage) -> Bool {
    if lhs.action != rhs.action {return false}
    if lhs.volume != rhs.volume {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension MediaControlMessage.Action: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0PLAY_PAUSE\0\u{1}NEXT\0\u{1}PREVIOUS\0\u{1}VOLUME_SET\0")
}

extension MediaArt: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "MediaArt"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}content\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.content) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.content.isEmpty {
      try visitor.visitSingularBytesField(value: self.content, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: MediaArt, rhs: MediaArt) -> Bool {
    if lhs.content != rhs.content {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension MediaPlaybackInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "MediaPlaybackInfo"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}playbackRate\0\u{1}duration\0\u{1}elapsed\0\u{1}title\0\u{1}album\0\u{1}artist\0\u{1}bundle\0\u{1}volume\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.playbackRate) }()
      case 2: try { try decoder.decodeSingularDoubleField(value: &self.duration) }()
      case 3: try { try decoder.decodeSingularDoubleField(value: &self.elapsed) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.title) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.album) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.artist) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.bundle) }()
      case 8: try { try decoder.decodeSingularFloatField(value: &self.volume) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.playbackRate != false {
      try visitor.visitSingularBoolField(value: self.playbackRate, fieldNumber: 1)
    }
    if self.duration.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.duration, fieldNumber: 2)
    }
    if self.elapsed.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.elapsed, fieldNumber: 3)
    }
    if !self.title.isEmpty {
      try visitor.visitSingularStringField(value: self.title, fieldNumber: 4)
    }
    if !self.album.isEmpty {
      try visitor.visitSingularStringField(value: self.album, fieldNumber: 5)
    }
    if !self.artist.isEmpty {
      try visitor.visitSingularStringField(value: self.artist, fieldNumber: 6)
    }
    if !self.bundle.isEmpty {
      try visitor.visitSingularStringField(value: self.bundle, fieldNumber: 7)
    }
    if self.volume.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.volume, fieldNumber: 8)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: MediaPlaybackInfo, rhs: MediaPlaybackInfo) -> Bool {
    if lhs.playbackRate != rhs.playbackRate {return false}
    if lhs.duration != rhs.duration {return false}
    if lhs.elapsed != rhs.elapsed {return false}
    if lhs.title != rhs.title {return false}
    if lhs.album != rhs.album {return false}
    if lhs.artist != rhs.artist {return false}
    if lhs.bundle != rhs.bundle {return false}
    if lhs.volume != rhs.volume {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension FileHeader: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "FileHeader"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}fileId\0\u{1}filename\0\u{1}filesizeBytes\0\u{1}metadata\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.fileID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.filename) }()
      case 3: try { try decoder.decodeSingularInt64Field(value: &self.filesizeBytes) }()
      case 4: try { try decoder.decodeSingularBytesField(value: &self.metadata) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.fileID.isEmpty {
      try visitor.visitSingularStringField(value: self.fileID, fieldNumber: 1)
    }
    if !self.filename.isEmpty {
      try visitor.visitSingularStringField(value: self.filename, fieldNumber: 2)
    }
    if self.filesizeBytes != 0 {
      try visitor.visitSingularInt64Field(value: self.filesizeBytes, fieldNumber: 3)
    }
    if !self.metadata.isEmpty {
      try visitor.visitSingularBytesField(value: self.metadata, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: FileHeader, rhs: FileHeader) -> Bool {
    if lhs.fileID != rhs.fileID {return false}
    if lhs.filename != rhs.filename {return false}
    if lhs.filesizeBytes != rhs.filesizeBytes {return false}
    if lhs.metadata != rhs.metadata {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension FileChunk: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "FileChunk"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}fileId\0\u{1}offset\0\u{1}data\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.fileID) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.offset) }()
      case 3: try { try decoder.decodeSingularBytesField(value: &self.data) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.fileID.isEmpty {
      try visitor.visitSingularStringField(value: self.fileID, fieldNumber: 1)
    }
    if self.offset != 0 {
      try visitor.visitSingularInt64Field(value: self.offset, fieldNumber: 2)
    }
    if !self.data.isEmpty {
      try visitor.visitSingularBytesField(value: self.data, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: FileChunk, rhs: FileChunk) -> Bool {
    if lhs.fileID != rhs.fileID {return false}
    if lhs.offset != rhs.offset {return false}
    if lhs.data != rhs.data {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension FileStatusRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "FileStatusRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}fileId\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.fileID) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.fileID.isEmpty {
      try visitor.visitSingularStringField(value: self.fileID, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: FileStatusRequest, rhs: FileStatusRequest) -> Bool {
    if lhs.fileID != rhs.fileID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension FileStatusResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "FileStatusResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}fileId\0\u{1}bytesRecieved\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.fileID) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.bytesRecieved) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.fileID.isEmpty {
      try visitor.visitSingularStringField(value: self.fileID, fieldNumber: 1)
    }
    if self.bytesRecieved != 0 {
      try visitor.visitSingularInt64Field(value: self.bytesRecieved, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: FileStatusResponse, rhs: FileStatusResponse) -> Bool {
    if lhs.fileID != rhs.fileID {return false}
    if lhs.bytesRecieved != rhs.bytesRecieved {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension FileTransferError: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "FileTransferError"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}fileId\0\u{1}error\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.fileID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.error) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.fileID.isEmpty {
      try visitor.visitSingularStringField(value: self.fileID, fieldNumber: 1)
    }
    if !self.error.isEmpty {
      try visitor.visitSingularStringField(value: self.error, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: FileTransferError, rhs: FileTransferError) -> Bool {
    if lhs.fileID != rhs.fileID {return false}
    if lhs.error != rhs.error {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Heartbeat: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "Heartbeat"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}isMediaPlaying\0\u{1}isMacUserActive\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.isMediaPlaying) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.isMacUserActive) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.isMediaPlaying != false {
      try visitor.visitSingularBoolField(value: self.isMediaPlaying, fieldNumber: 1)
    }
    if self.isMacUserActive != false {
      try visitor.visitSingularBoolField(value: self.isMacUserActive, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Heartbeat, rhs: Heartbeat) -> Bool {
    if lhs.isMediaPlaying != rhs.isMediaPlaying {return false}
    if lhs.isMacUserActive != rhs.isMacUserActive {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VideoStreamChunk: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "VideoStreamChunk"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}frame\0\u{1}presentationTimestampUs\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.frame) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.presentationTimestampUs) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.frame.isEmpty {
      try visitor.visitSingularBytesField(value: self.frame, fieldNumber: 1)
    }
    if self.presentationTimestampUs != 0 {
      try visitor.visitSingularInt64Field(value: self.presentationTimestampUs, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: VideoStreamChunk, rhs: VideoStreamChunk) -> Bool {
    if lhs.frame != rhs.frame {return false}
    if lhs.presentationTimestampUs != rhs.presentationTimestampUs {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
