//
//  ClipboardManager.swift
//  Passover
//
//  Created by Aakash Solanki on 24/08/24.
//

import Foundation
import AppKit
import os

extension NSPasteboard.PasteboardType {
    static let internalOrigin = NSPasteboard.PasteboardType("com.local.passover")
}

class ClipboardManager {
    private let pasteboard = NSPasteboard.general
    private var changeCount: Int
    private var timer: Timer?
    private var lastPublishHash: Int = -1
    
    private let sensitiveTypes = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType"
    ]

    var onClipboardUpdate: ((ClipboardMessage) -> Void)?

    init() {
        self.changeCount = pasteboard.changeCount
        startMonitoringClipboard()
    }

    deinit {
        timer?.invalidate()
        Logger.connection.debug("ClipboardManager deinit")
    }

    private func startMonitoringClipboard() {
        timer = Timer.scheduledTimer(withTimeInterval: 1.0, repeats: true) { [weak self] _ in
            self?.checkClipboard()
        }
    }

    private func checkClipboard() {
        guard pasteboard.changeCount != changeCount else { return }

        if pasteboard.availableType(from: [.internalOrigin]) != nil {
            changeCount = pasteboard.changeCount
            return
        }

        if let types = pasteboard.types?.map({ $0.rawValue }),
           types.contains(where: { sensitiveTypes.contains($0) }) {
            changeCount = pasteboard.changeCount
            return
        }

        var pendingImage: Data? = nil
        var pendingText: String? = nil

        if let imgData = pasteboard.data(forType: .png) ?? pasteboard.data(forType: .tiff) {
            pendingImage = imgData
        } else if let txt = pasteboard.string(forType: .string), !txt.isEmpty {
            pendingText = txt
        }

        changeCount = pasteboard.changeCount

        Task(priority: .userInitiated) {
            if let imgData = pendingImage {
                await processImage(imgData)
            } else if let txt = pendingText {
                handlePayload(txt, type: .txt)
            }
        }
    }

    func addDataToClipboard(data: ClipboardMessage) {
        pasteboard.clearContents()
        pasteboard.setString("", forType: .internalOrigin)

        switch data.type {
        case .txt:
            pasteboard.setString(data.content, forType: .string)
        case .img:
            if let decodedData = Data(base64Encoded: data.content) {
                pasteboard.setData(decodedData, forType: .png)
            }
        default: break
        }
        
        changeCount = pasteboard.changeCount
    }

    private func processImage(_ data: Data) async {
        guard let bitmap = NSBitmapImageRep(data: data),
              let pngData = bitmap.representation(using: .png, properties: [:]) else {
            return
        }

        let b64 = pngData.base64EncodedString()
        
        handlePayload(b64, type: .img)
    }

    private func handlePayload(_ payload: String, type: ClipboardMessage.ClipboardContentType) {
        guard lastPublishHash != payload.hashValue else {return}
        lastPublishHash = payload.hashValue

        let message = ClipboardMessage.with {
            $0.content = payload
            $0.type = type
        }
        onClipboardUpdate?(message)
    }
}
